CREATE TABLE VIEW_COURSE_OFFERING_TERM(
  TERM varchar(6) NOT NULL,
  CRN varchar(5) NOT NULL,
  COURSE varchar(21) DEFAULT NULL,
  DEPT varchar(4) DEFAULT NULL,
  SEC varchar(3) NOT NULL,
  TITLE varchar(100) DEFAULT NULL,
  AVIL int NOT NULL,
  M_ACT varchar(3) DEFAULT NULL,
  DAYS1 varchar(6) DEFAULT NULL,
  START1 varchar(4) DEFAULT NULL,
  END1 varchar(4) DEFAULT NULL,
  BLDG varchar(6) DEFAULT NULL,
  ROOM varchar(10) DEFAULT NULL,
  INSTR varchar(121) DEFAULT NULL
)



CREATE TABLE VIEW_STUDENT_SCHEDULE (
  TERM_CODE varchar(6) NOT NULL,
  STUDENT_ID varchar(9) NOT NULL,
  STU_SECTION_CRN varchar(5) NOT NULL
)


CREATE TABLE NAJAAH_EVENTS(
ID varchar NOT NULL,
TITLE varchar NOT NULL,
CRN varchar(5) NOT NULL,
START1 datetime2 NOT NULL,
END1 datetime2 NOT NULL,
NOTE varchar,
TYPE1 varchar NOT NULL
)




CREATE TABLE NAJAAH_EVENTS_REPEAT(
ID varchar NOT NULL,
DAYS1 binary(7) NOT NULL,
REPEAT_END datetime2 NOT NULL,
)

